# Dockerfile starter from https://github.com/thepeaklab/react-docker-multi-stage-example
#   + Updated the node version 12.14.0 (running locally), 
#   + Added installs for axios and semantic-ui-react
### STAGE 1: Build ###
FROM node:12.14.0 as build
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts -g --silent
RUN npm install axios --silent
RUN npm install semantic-ui-react
COPY . /usr/src/app
RUN npm run build

### STAGE 2: Production Environment ###
FROM nginx:1.13.12-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]